name: Advanced Matrix CI pipeline

on:
  push:
    branches:
      - main

jobs:
  python-test:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      # setup python
      - name: checkout code
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      # Cache Pip Dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{matrix.python-version}}
        
      # Install Dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint code
        run: |
          flake8 .
      
      - name: Run tests
        run: |
          pytest
      
